
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto generated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vide

open Browser.Types
open Vide

module HtmlElementBuilders =
    
    type HTMLGlobalAttrsElementBuilder<'n when 'n :> HTMLElement>(tagName) =
        inherit HTMLElementBuilder<'n>(tagName)
        member this.accesskey(value: System.String) = this.OnEval(fun x -> x.setAttribute("accesskey", value))
        member this.autocapitalize(value: string) = this.OnEval(fun x -> x.setAttribute("autocapitalize", value))
        member this.autofocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("autofocus", value))
        member this.className(value: System.String) = this.OnEval(fun x -> x.setAttribute("class", value))
        member this.contenteditable(value: System.Boolean) = this.OnEval(fun x -> x.setAttribute("contenteditable", value.ToString()))
        member this.contextmenu(value: System.String) = this.OnEval(fun x -> x.setAttribute("contextmenu", value))
        member this.dir(value: string) = this.OnEval(fun x -> x.setAttribute("dir", value))
        member this.draggable(value: System.Boolean) = this.OnEval(fun x -> x.setAttribute("draggable", value.ToString()))
        member this.enterkeyhint(value: System.String) = this.OnEval(fun x -> x.setAttribute("enterkeyhint", value))
        member this.exportparts(value: System.String) = this.OnEval(fun x -> x.setAttribute("exportparts", value))
        member this.hidden(value: System.String) = this.OnEval(fun x -> x.setAttribute("hidden", value))
        member this.id(value: System.String) = this.OnEval(fun x -> x.setAttribute("id", value))
        member this.inert(value: System.String) = this.OnEval(fun x -> x.setAttribute("inert", value))
        member this.inputmode(value: System.String) = this.OnEval(fun x -> x.setAttribute("inputmode", value))
        member this.is(value: System.String) = this.OnEval(fun x -> x.setAttribute("is", value))
        
        member this.onabort(handler) = this.OnInit(fun x -> x.onabort <- handler)
        member this.onblur(handler) = this.OnInit(fun x -> x.onblur <- handler)
        member this.oncanplay(handler) = this.OnInit(fun x -> x.oncanplay <- handler)
        member this.oncanplaythrough(handler) = this.OnInit(fun x -> x.oncanplaythrough <- handler)
        member this.onchange(handler) = this.OnInit(fun x -> x.onchange <- handler)
        member this.onclick(handler) = this.OnInit(fun x -> x.onclick <- handler)
        member this.oncontextmenu(handler) = this.OnInit(fun x -> x.oncontextmenu <- handler)
        member this.oncuechange(handler) = this.OnInit(fun x -> x.oncuechange <- handler)
        member this.ondblclick(handler) = this.OnInit(fun x -> x.ondblclick <- handler)
        member this.ondrag(handler) = this.OnInit(fun x -> x.ondrag <- handler)
        member this.ondragend(handler) = this.OnInit(fun x -> x.ondragend <- handler)
        member this.ondragenter(handler) = this.OnInit(fun x -> x.ondragenter <- handler)
        member this.ondragleave(handler) = this.OnInit(fun x -> x.ondragleave <- handler)
        member this.ondragover(handler) = this.OnInit(fun x -> x.ondragover <- handler)
        member this.ondragstart(handler) = this.OnInit(fun x -> x.ondragstart <- handler)
        member this.ondrop(handler) = this.OnInit(fun x -> x.ondrop <- handler)
        member this.ondurationchange(handler) = this.OnInit(fun x -> x.ondurationchange <- handler)
        member this.onemptied(handler) = this.OnInit(fun x -> x.onemptied <- handler)
        member this.onended(handler) = this.OnInit(fun x -> x.onended <- handler)
        member this.onerror(handler) = this.OnInit(fun x -> x.onerror <- handler)
        member this.onfocus(handler) = this.OnInit(fun x -> x.onfocus <- handler)
        member this.oninput(handler) = this.OnInit(fun x -> x.oninput <- handler)
        member this.onkeydown(handler) = this.OnInit(fun x -> x.onkeydown <- handler)
        member this.onkeypress(handler) = this.OnInit(fun x -> x.onkeypress <- handler)
        member this.onkeyup(handler) = this.OnInit(fun x -> x.onkeyup <- handler)
        member this.onload(handler) = this.OnInit(fun x -> x.onload <- handler)
        member this.onloadeddata(handler) = this.OnInit(fun x -> x.onloadeddata <- handler)
        member this.onloadedmetadata(handler) = this.OnInit(fun x -> x.onloadedmetadata <- handler)
        member this.onloadstart(handler) = this.OnInit(fun x -> x.onloadstart <- handler)
        member this.onmousedown(handler) = this.OnInit(fun x -> x.onmousedown <- handler)
        member this.onmouseenter(handler) = this.OnInit(fun x -> x.onmouseenter <- handler)
        member this.onmouseleave(handler) = this.OnInit(fun x -> x.onmouseleave <- handler)
        member this.onmousemove(handler) = this.OnInit(fun x -> x.onmousemove <- handler)
        member this.onmouseout(handler) = this.OnInit(fun x -> x.onmouseout <- handler)
        member this.onmouseover(handler) = this.OnInit(fun x -> x.onmouseover <- handler)
        member this.onmouseup(handler) = this.OnInit(fun x -> x.onmouseup <- handler)
        member this.onmousewheel(handler) = this.OnInit(fun x -> x.onmousewheel <- handler)
        member this.onpause(handler) = this.OnInit(fun x -> x.onpause <- handler)
        member this.onplay(handler) = this.OnInit(fun x -> x.onplay <- handler)
        member this.onplaying(handler) = this.OnInit(fun x -> x.onplaying <- handler)
        member this.onprogress(handler) = this.OnInit(fun x -> x.onprogress <- handler)
        member this.onratechange(handler) = this.OnInit(fun x -> x.onratechange <- handler)
        member this.onreset(handler) = this.OnInit(fun x -> x.onreset <- handler)
        member this.onscroll(handler) = this.OnInit(fun x -> x.onscroll <- handler)
        member this.onseeked(handler) = this.OnInit(fun x -> x.onseeked <- handler)
        member this.onseeking(handler) = this.OnInit(fun x -> x.onseeking <- handler)
        member this.onselect(handler) = this.OnInit(fun x -> x.onselect <- handler)
        member this.onstalled(handler) = this.OnInit(fun x -> x.onstalled <- handler)
        member this.onsubmit(handler) = this.OnInit(fun x -> x.onsubmit <- handler)
        member this.onsuspend(handler) = this.OnInit(fun x -> x.onsuspend <- handler)
        member this.ontimeupdate(handler) = this.OnInit(fun x -> x.ontimeupdate <- handler)
        member this.onvolumechange(handler) = this.OnInit(fun x -> x.onvolumechange <- handler)
        member this.onwaiting(handler) = this.OnInit(fun x -> x.onwaiting <- handler)
        
    
    type html() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHtmlElement>( " "elem.name" " )
        member this.manifest(value: System.String) = this.OnEval(fun x -> x.setAttribute("manifest", value))
        member this.version(value: System.String) = this.OnEval(fun x -> x.setAttribute("version", value))
        member this.xmlns(value: System.String) = this.OnEval(fun x -> x.setAttribute("xmlns", value))
        
        
    
    type head() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadElement>( " "elem.name" " )
        member this.profile(value: System.String) = this.OnEval(fun x -> x.setAttribute("profile", value))
        
        
    
    type link() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLLinkElement>( " "elem.name" " )
        member this.as'(value: System.String) = this.OnEval(fun x -> x.setAttribute("as", value))
        member this.crossorigin(value: string) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.fetchpriority(value: string) = this.OnEval(fun x -> x.setAttribute("fetchpriority", value))
        member this.href(value: System.String) = this.OnEval(fun x -> x.setAttribute("href", value))
        member this.hreflang(value: System.String) = this.OnEval(fun x -> x.setAttribute("hreflang", value))
        member this.imagesizes(value: System.String) = this.OnEval(fun x -> x.setAttribute("imagesizes", value))
        member this.imagesrcset(value: System.String) = this.OnEval(fun x -> x.setAttribute("imagesrcset", value))
        member this.integrity(value: System.String) = this.OnEval(fun x -> x.setAttribute("integrity", value))
        member this.media(value: System.String) = this.OnEval(fun x -> x.setAttribute("media", value))
        member this.prefetch(value: System.String) = this.OnEval(fun x -> x.setAttribute("prefetch", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.rel(value: System.String) = this.OnEval(fun x -> x.setAttribute("rel", value))
        member this.sizes(value: string) = this.OnEval(fun x -> x.setAttribute("sizes", value))
        member this.title(value: System.String) = this.OnEval(fun x -> x.setAttribute("title", value))
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.blocking(value: string) = this.OnEval(fun x -> x.setAttribute("blocking", value))
        
        
    
    type meta() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLMetaElement>( " "elem.name" " )
        member this.charset(value: System.String) = this.OnEval(fun x -> x.setAttribute("charset", value))
        member this.content(value: System.String) = this.OnEval(fun x -> x.setAttribute("content", value))
        member this.httpEquiv(value: string) = this.OnEval(fun x -> x.setAttribute("http-equiv", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        
        
    
    type style() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLStyleElement>( " "elem.name" " )
        member this.media(value: System.String) = this.OnEval(fun x -> x.setAttribute("media", value))
        member this.nonce(value: System.String) = this.OnEval(fun x -> x.setAttribute("nonce", value))
        member this.title(value: System.String) = this.OnEval(fun x -> x.setAttribute("title", value))
        member this.blocking(value: string) = this.OnEval(fun x -> x.setAttribute("blocking", value))
        
        
    
    type title() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTitleElement>( " "elem.name" " )
        
        
    
    type body() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLBodyElement>( " "elem.name" " )
        member this.alink(value: System.String) = this.OnEval(fun x -> x.setAttribute("alink", value))
        member this.background(value: System.String) = this.OnEval(fun x -> x.setAttribute("background", value))
        member this.bgcolor(value: System.String) = this.OnEval(fun x -> x.setAttribute("bgcolor", value))
        member this.bottommargin(value: System.String) = this.OnEval(fun x -> x.setAttribute("bottommargin", value))
        member this.leftmargin(value: System.String) = this.OnEval(fun x -> x.setAttribute("leftmargin", value))
        member this.link(value: System.String) = this.OnEval(fun x -> x.setAttribute("link", value))
        member this.onafterprint(value: System.String) = this.OnEval(fun x -> x.setAttribute("onafterprint", value))
        member this.onbeforeprint(value: System.String) = this.OnEval(fun x -> x.setAttribute("onbeforeprint", value))
        member this.onbeforeunload(value: System.String) = this.OnEval(fun x -> x.setAttribute("onbeforeunload", value))
        member this.onblur(value: System.String) = this.OnEval(fun x -> x.setAttribute("onblur", value))
        member this.onerror(value: System.String) = this.OnEval(fun x -> x.setAttribute("onerror", value))
        member this.onfocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("onfocus", value))
        member this.onhashchange(value: System.String) = this.OnEval(fun x -> x.setAttribute("onhashchange", value))
        member this.onlanguagechange(value: System.String) = this.OnEval(fun x -> x.setAttribute("onlanguagechange", value))
        member this.onload(value: System.String) = this.OnEval(fun x -> x.setAttribute("onload", value))
        member this.onmessage(value: System.String) = this.OnEval(fun x -> x.setAttribute("onmessage", value))
        member this.onoffline(value: System.String) = this.OnEval(fun x -> x.setAttribute("onoffline", value))
        member this.ononline(value: System.String) = this.OnEval(fun x -> x.setAttribute("ononline", value))
        member this.onpopstate(value: System.String) = this.OnEval(fun x -> x.setAttribute("onpopstate", value))
        member this.onredo(value: System.String) = this.OnEval(fun x -> x.setAttribute("onredo", value))
        member this.onresize(value: System.String) = this.OnEval(fun x -> x.setAttribute("onresize", value))
        member this.onstorage(value: System.String) = this.OnEval(fun x -> x.setAttribute("onstorage", value))
        member this.onundo(value: System.String) = this.OnEval(fun x -> x.setAttribute("onundo", value))
        member this.onunload(value: System.String) = this.OnEval(fun x -> x.setAttribute("onunload", value))
        member this.rightmargin(value: System.String) = this.OnEval(fun x -> x.setAttribute("rightmargin", value))
        member this.text(value: System.String) = this.OnEval(fun x -> x.setAttribute("text", value))
        member this.topmargin(value: System.String) = this.OnEval(fun x -> x.setAttribute("topmargin", value))
        member this.vlink(value: System.String) = this.OnEval(fun x -> x.setAttribute("vlink", value))
        
        
    
    type address() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type article() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type aside() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type footer() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type header() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type h1() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( " "elem.name" " )
        
        
    
    type h2() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( " "elem.name" " )
        
        
    
    type h3() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( " "elem.name" " )
        
        
    
    type h4() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( " "elem.name" " )
        
        
    
    type h5() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( " "elem.name" " )
        
        
    
    type h6() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( " "elem.name" " )
        
        
    
    type main() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type nav() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type section() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type blockquote() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLQuoteElement>( " "elem.name" " )
        member this.cite(value: System.String) = this.OnEval(fun x -> x.setAttribute("cite", value))
        
        
    
    type dd() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        member this.nowrap(value: System.String) = this.OnEval(fun x -> x.setAttribute("nowrap", value))
        
        
    
    type div() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLDivElement>( " "elem.name" " )
        
        
    
    type dl() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLDListElement>( " "elem.name" " )
        
        
    
    type dt() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type figcaption() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type figure() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type hr() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHRElement>( " "elem.name" " )
        member this.align(value: System.String) = this.OnEval(fun x -> x.setAttribute("align", value))
        member this.color(value: System.String) = this.OnEval(fun x -> x.setAttribute("color", value))
        member this.noshade(value: System.String) = this.OnEval(fun x -> x.setAttribute("noshade", value))
        member this.size(value: System.String) = this.OnEval(fun x -> x.setAttribute("size", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type li() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLLIElement>( " "elem.name" " )
        member this.value(value: System.String) = this.OnEval(fun x -> x.setAttribute("value", value))
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type menu() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLMenuElement>( " "elem.name" " )
        
        
    
    type ol() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLOListElement>( " "elem.name" " )
        member this.reversed(value: System.String) = this.OnEval(fun x -> x.setAttribute("reversed", value))
        member this.start(value: System.String) = this.OnEval(fun x -> x.setAttribute("start", value))
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type p() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLParagraphElement>( " "elem.name" " )
        
        
    
    type pre() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLPreElement>( " "elem.name" " )
        member this.cols(value: System.String) = this.OnEval(fun x -> x.setAttribute("cols", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        member this.wrap(value: System.String) = this.OnEval(fun x -> x.setAttribute("wrap", value))
        
        
    
    type ul() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLUListElement>( " "elem.name" " )
        member this.compact(value: System.String) = this.OnEval(fun x -> x.setAttribute("compact", value))
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type a() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLAnchorElement>( " "elem.name" " )
        member this.download(value: string) = this.OnEval(fun x -> x.setAttribute("download", value))
        member this.href(value: string) = this.OnEval(fun x -> x.setAttribute("href", value))
        member this.hreflang(value: System.String) = this.OnEval(fun x -> x.setAttribute("hreflang", value))
        member this.ping(value: System.String) = this.OnEval(fun x -> x.setAttribute("ping", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.rel(value: System.String) = this.OnEval(fun x -> x.setAttribute("rel", value))
        member this.target(value: string) = this.OnEval(fun x -> x.setAttribute("target", value))
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type abbr() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type b() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type bdi() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type bdo() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        member this.dir(value: string) = this.OnEval(fun x -> x.setAttribute("dir", value))
        
        
    
    type br() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLBRElement>( " "elem.name" " )
        
        
    
    type cite() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type code() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type dfn() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type em() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type i() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type kbd() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type mark() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type q() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLQuoteElement>( " "elem.name" " )
        member this.cite(value: System.String) = this.OnEval(fun x -> x.setAttribute("cite", value))
        
        
    
    type rp() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type rt() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type ruby() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type s() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type samp() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type small() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type span() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLSpanElement>( " "elem.name" " )
        
        
    
    type strong() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type sub() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type sup() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type u() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type var() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type wbr() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type area() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLAreaElement>( " "elem.name" " )
        member this.alt(value: System.String) = this.OnEval(fun x -> x.setAttribute("alt", value))
        member this.coords(value: string) = this.OnEval(fun x -> x.setAttribute("coords", value))
        member this.download(value: System.String) = this.OnEval(fun x -> x.setAttribute("download", value))
        member this.href(value: System.String) = this.OnEval(fun x -> x.setAttribute("href", value))
        member this.hreflang(value: System.String) = this.OnEval(fun x -> x.setAttribute("hreflang", value))
        member this.ping(value: System.String) = this.OnEval(fun x -> x.setAttribute("ping", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.rel(value: System.String) = this.OnEval(fun x -> x.setAttribute("rel", value))
        member this.shape(value: System.String) = this.OnEval(fun x -> x.setAttribute("shape", value))
        member this.target(value: string) = this.OnEval(fun x -> x.setAttribute("target", value))
        
        
    
    type audio() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLAudioElement>( " "elem.name" " )
        member this.autoplay(value: System.String) = this.OnEval(fun x -> x.setAttribute("autoplay", value))
        member this.controls(value: System.String) = this.OnEval(fun x -> x.setAttribute("controls", value))
        member this.controlslist(value: System.String) = this.OnEval(fun x -> x.setAttribute("controlslist", value))
        member this.crossorigin(value: string) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.disableremoteplayback(value: System.String) = this.OnEval(fun x -> x.setAttribute("disableremoteplayback", value))
        member this.loop(value: System.String) = this.OnEval(fun x -> x.setAttribute("loop", value))
        member this.muted(value: System.String) = this.OnEval(fun x -> x.setAttribute("muted", value))
        member this.preload(value: string) = this.OnEval(fun x -> x.setAttribute("preload", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        
        
    
    type img() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLImageElement>( " "elem.name" " )
        member this.alt(value: System.String) = this.OnEval(fun x -> x.setAttribute("alt", value))
        member this.crossorigin(value: string) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.decoding(value: string) = this.OnEval(fun x -> x.setAttribute("decoding", value))
        member this.fetchpriority(value: string) = this.OnEval(fun x -> x.setAttribute("fetchpriority", value))
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.ismap(value: System.String) = this.OnEval(fun x -> x.setAttribute("ismap", value))
        member this.loading(value: string) = this.OnEval(fun x -> x.setAttribute("loading", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.sizes(value: System.String) = this.OnEval(fun x -> x.setAttribute("sizes", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.srcset(value: System.String) = this.OnEval(fun x -> x.setAttribute("srcset", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        member this.usemap(value: System.String) = this.OnEval(fun x -> x.setAttribute("usemap", value))
        
        
    
    type map() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLMapElement>( " "elem.name" " )
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        
        
    
    type track() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTrackElement>( " "elem.name" " )
        member this.default'(value: System.String) = this.OnEval(fun x -> x.setAttribute("default", value))
        member this.kind(value: string) = this.OnEval(fun x -> x.setAttribute("kind", value))
        member this.label(value: System.String) = this.OnEval(fun x -> x.setAttribute("label", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.srclang(value: System.String) = this.OnEval(fun x -> x.setAttribute("srclang", value))
        
        
    
    type video() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLVideoElement>( " "elem.name" " )
        member this.autoplay(value: System.String) = this.OnEval(fun x -> x.setAttribute("autoplay", value))
        member this.autopictureinpicture(value: System.String) = this.OnEval(fun x -> x.setAttribute("autopictureinpicture", value))
        member this.controls(value: System.String) = this.OnEval(fun x -> x.setAttribute("controls", value))
        member this.controlslist(value: System.String) = this.OnEval(fun x -> x.setAttribute("controlslist", value))
        member this.crossorigin(value: string) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.disablepictureinpicture(value: System.String) = this.OnEval(fun x -> x.setAttribute("disablepictureinpicture", value))
        member this.disableremoteplayback(value: System.String) = this.OnEval(fun x -> x.setAttribute("disableremoteplayback", value))
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.loop(value: System.String) = this.OnEval(fun x -> x.setAttribute("loop", value))
        member this.muted(value: System.String) = this.OnEval(fun x -> x.setAttribute("muted", value))
        member this.playsinline(value: System.String) = this.OnEval(fun x -> x.setAttribute("playsinline", value))
        member this.poster(value: System.String) = this.OnEval(fun x -> x.setAttribute("poster", value))
        member this.preload(value: string) = this.OnEval(fun x -> x.setAttribute("preload", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type embed() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLEmbedElement>( " "elem.name" " )
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type iframe() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLIFrameElement>( " "elem.name" " )
        member this.allow(value: System.String) = this.OnEval(fun x -> x.setAttribute("allow", value))
        member this.allowfullscreen(value: System.String) = this.OnEval(fun x -> x.setAttribute("allowfullscreen", value))
        member this.allowpaymentrequest(value: System.String) = this.OnEval(fun x -> x.setAttribute("allowpaymentrequest", value))
        member this.credentialless(value: System.String) = this.OnEval(fun x -> x.setAttribute("credentialless", value))
        member this.csp(value: System.String) = this.OnEval(fun x -> x.setAttribute("csp", value))
        member this.fetchpriority(value: string) = this.OnEval(fun x -> x.setAttribute("fetchpriority", value))
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.loading(value: string) = this.OnEval(fun x -> x.setAttribute("loading", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.sandbox(value: string) = this.OnEval(fun x -> x.setAttribute("sandbox", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.srcdoc(value: System.String) = this.OnEval(fun x -> x.setAttribute("srcdoc", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type object() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLObjectElement>( " "elem.name" " )
        member this.archive(value: System.String) = this.OnEval(fun x -> x.setAttribute("archive", value))
        member this.border(value: System.String) = this.OnEval(fun x -> x.setAttribute("border", value))
        member this.classid(value: System.String) = this.OnEval(fun x -> x.setAttribute("classid", value))
        member this.codebase(value: System.String) = this.OnEval(fun x -> x.setAttribute("codebase", value))
        member this.codetype(value: System.String) = this.OnEval(fun x -> x.setAttribute("codetype", value))
        member this.data(value: System.String) = this.OnEval(fun x -> x.setAttribute("data", value))
        member this.declare(value: System.String) = this.OnEval(fun x -> x.setAttribute("declare", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.standby(value: System.String) = this.OnEval(fun x -> x.setAttribute("standby", value))
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.usemap(value: System.String) = this.OnEval(fun x -> x.setAttribute("usemap", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type source() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLSourceElement>( " "elem.name" " )
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.srcset(value: System.String) = this.OnEval(fun x -> x.setAttribute("srcset", value))
        member this.sizes(value: System.String) = this.OnEval(fun x -> x.setAttribute("sizes", value))
        member this.media(value: System.String) = this.OnEval(fun x -> x.setAttribute("media", value))
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type canvas() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLCanvasElement>( " "elem.name" " )
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.mozOpaque(value: System.String) = this.OnEval(fun x -> x.setAttribute("moz-opaque", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type noscript() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    
    type script() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLScriptElement>( " "elem.name" " )
        member this.async(value: System.String) = this.OnEval(fun x -> x.setAttribute("async", value))
        member this.crossorigin(value: System.String) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.defer(value: System.String) = this.OnEval(fun x -> x.setAttribute("defer", value))
        member this.fetchpriority(value: string) = this.OnEval(fun x -> x.setAttribute("fetchpriority", value))
        member this.integrity(value: System.String) = this.OnEval(fun x -> x.setAttribute("integrity", value))
        member this.nomodule(value: System.String) = this.OnEval(fun x -> x.setAttribute("nomodule", value))
        member this.nonce(value: System.String) = this.OnEval(fun x -> x.setAttribute("nonce", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.blocking(value: string) = this.OnEval(fun x -> x.setAttribute("blocking", value))
        
        
    
    type del() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLModElement>( " "elem.name" " )
        member this.cite(value: System.String) = this.OnEval(fun x -> x.setAttribute("cite", value))
        member this.datetime(value: System.String) = this.OnEval(fun x -> x.setAttribute("datetime", value))
        
        
    
    type ins() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLModElement>( " "elem.name" " )
        member this.cite(value: System.String) = this.OnEval(fun x -> x.setAttribute("cite", value))
        member this.datetime(value: System.String) = this.OnEval(fun x -> x.setAttribute("datetime", value))
        
        
    
    type caption() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableCaptionElement>( " "elem.name" " )
        
        
    
    type col() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableColElement>( " "elem.name" " )
        member this.span(value: System.String) = this.OnEval(fun x -> x.setAttribute("span", value))
        
        
    
    type colgroup() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableColElement>( " "elem.name" " )
        member this.span(value: System.String) = this.OnEval(fun x -> x.setAttribute("span", value))
        
        
    
    type table() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableElement>( " "elem.name" " )
        
        
    
    type tbody() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableSectionElement>( " "elem.name" " )
        
        
    
    type td() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableCellElement>( " "elem.name" " )
        member this.colspan(value: System.String) = this.OnEval(fun x -> x.setAttribute("colspan", value))
        member this.headers(value: System.String) = this.OnEval(fun x -> x.setAttribute("headers", value))
        member this.rowspan(value: System.String) = this.OnEval(fun x -> x.setAttribute("rowspan", value))
        
        
    
    type tfoot() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableSectionElement>( " "elem.name" " )
        
        
    
    type th() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableCellElement>( " "elem.name" " )
        member this.abbr(value: System.String) = this.OnEval(fun x -> x.setAttribute("abbr", value))
        member this.colspan(value: System.String) = this.OnEval(fun x -> x.setAttribute("colspan", value))
        member this.headers(value: System.String) = this.OnEval(fun x -> x.setAttribute("headers", value))
        member this.rowspan(value: System.String) = this.OnEval(fun x -> x.setAttribute("rowspan", value))
        member this.scope(value: string) = this.OnEval(fun x -> x.setAttribute("scope", value))
        
        
    
    type thead() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableSectionElement>( " "elem.name" " )
        
        
    
    type tr() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableRowElement>( " "elem.name" " )
        
        
    
    type button() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLButtonElement>( " "elem.name" " )
        member this.autofocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("autofocus", value))
        member this.autocomplete(value: System.String) = this.OnEval(fun x -> x.setAttribute("autocomplete", value))
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.formaction(value: System.String) = this.OnEval(fun x -> x.setAttribute("formaction", value))
        member this.formenctype(value: string) = this.OnEval(fun x -> x.setAttribute("formenctype", value))
        member this.formmethod(value: string) = this.OnEval(fun x -> x.setAttribute("formmethod", value))
        member this.formnovalidate(value: System.String) = this.OnEval(fun x -> x.setAttribute("formnovalidate", value))
        member this.formtarget(value: string) = this.OnEval(fun x -> x.setAttribute("formtarget", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.value(value: System.String) = this.OnEval(fun x -> x.setAttribute("value", value))
        
        
    
    type datalist() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLDataListElement>( " "elem.name" " )
        
        
    
    type fieldset() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLFieldSetElement>( " "elem.name" " )
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        
        
    
    type form() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLFormElement>( " "elem.name" " )
        member this.accept(value: System.String) = this.OnEval(fun x -> x.setAttribute("accept", value))
        member this.acceptCharset(value: System.String) = this.OnEval(fun x -> x.setAttribute("accept-charset", value))
        member this.autocapitalize(value: string) = this.OnEval(fun x -> x.setAttribute("autocapitalize", value))
        member this.autocomplete(value: string) = this.OnEval(fun x -> x.setAttribute("autocomplete", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.rel(value: System.String) = this.OnEval(fun x -> x.setAttribute("rel", value))
        
        
    
    type input() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLInputElement>( " "elem.name" " )
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type label() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLLabelElement>( " "elem.name" " )
        member this.for'(value: System.String) = this.OnEval(fun x -> x.setAttribute("for", value))
        
        
    
    type legend() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLLegendElement>( " "elem.name" " )
        
        
    
    type optgroup() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLOptGroupElement>( " "elem.name" " )
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.label(value: System.String) = this.OnEval(fun x -> x.setAttribute("label", value))
        
        
    
    type option() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLOptionElement>( " "elem.name" " )
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.label(value: System.String) = this.OnEval(fun x -> x.setAttribute("label", value))
        member this.selected(value: System.String) = this.OnEval(fun x -> x.setAttribute("selected", value))
        member this.value(value: System.String) = this.OnEval(fun x -> x.setAttribute("value", value))
        
        
    
    type progress() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLProgressElement>( " "elem.name" " )
        member this.max(value: System.String) = this.OnEval(fun x -> x.setAttribute("max", value))
        member this.value(value: System.String) = this.OnEval(fun x -> x.setAttribute("value", value))
        
        
    
    type select() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLSelectElement>( " "elem.name" " )
        member this.autocomplete(value: System.String) = this.OnEval(fun x -> x.setAttribute("autocomplete", value))
        member this.autofocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("autofocus", value))
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.multiple(value: System.String) = this.OnEval(fun x -> x.setAttribute("multiple", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.required(value: System.String) = this.OnEval(fun x -> x.setAttribute("required", value))
        member this.size(value: System.String) = this.OnEval(fun x -> x.setAttribute("size", value))
        
        
    
    type textarea() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTextAreaElement>( " "elem.name" " )
        member this.autocomplete(value: string) = this.OnEval(fun x -> x.setAttribute("autocomplete", value))
        member this.autocorrect(value: string) = this.OnEval(fun x -> x.setAttribute("autocorrect", value))
        member this.autofocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("autofocus", value))
        member this.cols(value: System.String) = this.OnEval(fun x -> x.setAttribute("cols", value))
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.maxlength(value: System.String) = this.OnEval(fun x -> x.setAttribute("maxlength", value))
        member this.minlength(value: System.String) = this.OnEval(fun x -> x.setAttribute("minlength", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.placeholder(value: System.String) = this.OnEval(fun x -> x.setAttribute("placeholder", value))
        member this.readonly(value: System.String) = this.OnEval(fun x -> x.setAttribute("readonly", value))
        member this.required(value: System.String) = this.OnEval(fun x -> x.setAttribute("required", value))
        member this.rows(value: System.String) = this.OnEval(fun x -> x.setAttribute("rows", value))
        member this.spellcheck(value: string) = this.OnEval(fun x -> x.setAttribute("spellcheck", value))
        member this.wrap(value: string) = this.OnEval(fun x -> x.setAttribute("wrap", value))
        
        
    
    type summary() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( " "elem.name" " )
        
        
    

type Html =
    static member inline HTMLGlobalAttrsElementBuilder = HtmlElementBuilders.HTMLGlobalAttrsElementBuilder()
    static member inline html = HtmlElementBuilders. "elem.name" ()
    static member inline head = HtmlElementBuilders. "elem.name" ()
    static member inline link = HtmlElementBuilders. "elem.name" ()
    static member inline meta = HtmlElementBuilders. "elem.name" ()
    static member inline style = HtmlElementBuilders. "elem.name" ()
    static member inline title = HtmlElementBuilders. "elem.name" ()
    static member inline body = HtmlElementBuilders. "elem.name" ()
    static member inline address = HtmlElementBuilders. "elem.name" ()
    static member inline article = HtmlElementBuilders. "elem.name" ()
    static member inline aside = HtmlElementBuilders. "elem.name" ()
    static member inline footer = HtmlElementBuilders. "elem.name" ()
    static member inline header = HtmlElementBuilders. "elem.name" ()
    static member inline h1 = HtmlElementBuilders. "elem.name" ()
    static member inline h2 = HtmlElementBuilders. "elem.name" ()
    static member inline h3 = HtmlElementBuilders. "elem.name" ()
    static member inline h4 = HtmlElementBuilders. "elem.name" ()
    static member inline h5 = HtmlElementBuilders. "elem.name" ()
    static member inline h6 = HtmlElementBuilders. "elem.name" ()
    static member inline main = HtmlElementBuilders. "elem.name" ()
    static member inline nav = HtmlElementBuilders. "elem.name" ()
    static member inline section = HtmlElementBuilders. "elem.name" ()
    static member inline blockquote = HtmlElementBuilders. "elem.name" ()
    static member inline dd = HtmlElementBuilders. "elem.name" ()
    static member inline div = HtmlElementBuilders. "elem.name" ()
    static member inline dl = HtmlElementBuilders. "elem.name" ()
    static member inline dt = HtmlElementBuilders. "elem.name" ()
    static member inline figcaption = HtmlElementBuilders. "elem.name" ()
    static member inline figure = HtmlElementBuilders. "elem.name" ()
    static member inline hr = HtmlElementBuilders. "elem.name" ()
    static member inline li = HtmlElementBuilders. "elem.name" ()
    static member inline menu = HtmlElementBuilders. "elem.name" ()
    static member inline ol = HtmlElementBuilders. "elem.name" ()
    static member inline p = HtmlElementBuilders. "elem.name" ()
    static member inline pre = HtmlElementBuilders. "elem.name" ()
    static member inline ul = HtmlElementBuilders. "elem.name" ()
    static member inline a = HtmlElementBuilders. "elem.name" ()
    static member inline abbr = HtmlElementBuilders. "elem.name" ()
    static member inline b = HtmlElementBuilders. "elem.name" ()
    static member inline bdi = HtmlElementBuilders. "elem.name" ()
    static member inline bdo = HtmlElementBuilders. "elem.name" ()
    static member inline br = HtmlElementBuilders. "elem.name" ()
    static member inline cite = HtmlElementBuilders. "elem.name" ()
    static member inline code = HtmlElementBuilders. "elem.name" ()
    static member inline dfn = HtmlElementBuilders. "elem.name" ()
    static member inline em = HtmlElementBuilders. "elem.name" ()
    static member inline i = HtmlElementBuilders. "elem.name" ()
    static member inline kbd = HtmlElementBuilders. "elem.name" ()
    static member inline mark = HtmlElementBuilders. "elem.name" ()
    static member inline q = HtmlElementBuilders. "elem.name" ()
    static member inline rp = HtmlElementBuilders. "elem.name" ()
    static member inline rt = HtmlElementBuilders. "elem.name" ()
    static member inline ruby = HtmlElementBuilders. "elem.name" ()
    static member inline s = HtmlElementBuilders. "elem.name" ()
    static member inline samp = HtmlElementBuilders. "elem.name" ()
    static member inline small = HtmlElementBuilders. "elem.name" ()
    static member inline span = HtmlElementBuilders. "elem.name" ()
    static member inline strong = HtmlElementBuilders. "elem.name" ()
    static member inline sub = HtmlElementBuilders. "elem.name" ()
    static member inline sup = HtmlElementBuilders. "elem.name" ()
    static member inline u = HtmlElementBuilders. "elem.name" ()
    static member inline var = HtmlElementBuilders. "elem.name" ()
    static member inline wbr = HtmlElementBuilders. "elem.name" ()
    static member inline area = HtmlElementBuilders. "elem.name" ()
    static member inline audio = HtmlElementBuilders. "elem.name" ()
    static member inline img = HtmlElementBuilders. "elem.name" ()
    static member inline map = HtmlElementBuilders. "elem.name" ()
    static member inline track = HtmlElementBuilders. "elem.name" ()
    static member inline video = HtmlElementBuilders. "elem.name" ()
    static member inline embed = HtmlElementBuilders. "elem.name" ()
    static member inline iframe = HtmlElementBuilders. "elem.name" ()
    static member inline object = HtmlElementBuilders. "elem.name" ()
    static member inline source = HtmlElementBuilders. "elem.name" ()
    static member inline canvas = HtmlElementBuilders. "elem.name" ()
    static member inline noscript = HtmlElementBuilders. "elem.name" ()
    static member inline script = HtmlElementBuilders. "elem.name" ()
    static member inline del = HtmlElementBuilders. "elem.name" ()
    static member inline ins = HtmlElementBuilders. "elem.name" ()
    static member inline caption = HtmlElementBuilders. "elem.name" ()
    static member inline col = HtmlElementBuilders. "elem.name" ()
    static member inline colgroup = HtmlElementBuilders. "elem.name" ()
    static member inline table = HtmlElementBuilders. "elem.name" ()
    static member inline tbody = HtmlElementBuilders. "elem.name" ()
    static member inline td = HtmlElementBuilders. "elem.name" ()
    static member inline tfoot = HtmlElementBuilders. "elem.name" ()
    static member inline th = HtmlElementBuilders. "elem.name" ()
    static member inline thead = HtmlElementBuilders. "elem.name" ()
    static member inline tr = HtmlElementBuilders. "elem.name" ()
    static member inline button = HtmlElementBuilders. "elem.name" ()
    static member inline datalist = HtmlElementBuilders. "elem.name" ()
    static member inline fieldset = HtmlElementBuilders. "elem.name" ()
    static member inline form = HtmlElementBuilders. "elem.name" ()
    static member inline input = HtmlElementBuilders. "elem.name" ()
    static member inline label = HtmlElementBuilders. "elem.name" ()
    static member inline legend = HtmlElementBuilders. "elem.name" ()
    static member inline optgroup = HtmlElementBuilders. "elem.name" ()
    static member inline option = HtmlElementBuilders. "elem.name" ()
    static member inline progress = HtmlElementBuilders. "elem.name" ()
    static member inline select = HtmlElementBuilders. "elem.name" ()
    static member inline textarea = HtmlElementBuilders. "elem.name" ()
    static member inline summary = HtmlElementBuilders. "elem.name" ()
    
