
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto generated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vide

open Browser.Types
open Vide

module HtmlElementBuilders =
    
    type HTMLGlobalAttrsElementBuilder<'n when 'n :> HTMLElement>(tagName) =
        inherit HTMLElementBuilder<'n>(tagName)
        member this.accesskey(value: System.String) = this.OnEval(fun x -> x.setAttribute("accesskey", value))
        member this.autocapitalize(value: string) = this.OnEval(fun x -> x.setAttribute("autocapitalize", value))
        member this.autofocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("autofocus", value))
        member this.className(value: System.String) = this.OnEval(fun x -> x.setAttribute("class", value))
        member this.contenteditable(value: System.Boolean) = this.OnEval(fun x -> x.setAttribute("contenteditable", value.ToString()))
        member this.contextmenu(value: System.String) = this.OnEval(fun x -> x.setAttribute("contextmenu", value))
        member this.dir(value: string) = this.OnEval(fun x -> x.setAttribute("dir", value))
        member this.draggable(value: System.Boolean) = this.OnEval(fun x -> x.setAttribute("draggable", value.ToString()))
        member this.enterkeyhint(value: System.String) = this.OnEval(fun x -> x.setAttribute("enterkeyhint", value))
        member this.exportparts(value: System.String) = this.OnEval(fun x -> x.setAttribute("exportparts", value))
        member this.hidden(value: System.String) = this.OnEval(fun x -> x.setAttribute("hidden", value))
        member this.id(value: System.String) = this.OnEval(fun x -> x.setAttribute("id", value))
        member this.inert(value: System.String) = this.OnEval(fun x -> x.setAttribute("inert", value))
        member this.inputmode(value: System.String) = this.OnEval(fun x -> x.setAttribute("inputmode", value))
        member this.is(value: System.String) = this.OnEval(fun x -> x.setAttribute("is", value))
        
        member this.onabort(handler) = this.OnInit(fun x -> x.onabort <- handler)
        member this.onblur(handler) = this.OnInit(fun x -> x.onblur <- handler)
        member this.oncanplay(handler) = this.OnInit(fun x -> x.oncanplay <- handler)
        member this.oncanplaythrough(handler) = this.OnInit(fun x -> x.oncanplaythrough <- handler)
        member this.onchange(handler) = this.OnInit(fun x -> x.onchange <- handler)
        member this.onclick(handler) = this.OnInit(fun x -> x.onclick <- handler)
        member this.oncontextmenu(handler) = this.OnInit(fun x -> x.oncontextmenu <- handler)
        member this.oncuechange(handler) = this.OnInit(fun x -> x.oncuechange <- handler)
        member this.ondblclick(handler) = this.OnInit(fun x -> x.ondblclick <- handler)
        member this.ondrag(handler) = this.OnInit(fun x -> x.ondrag <- handler)
        member this.ondragend(handler) = this.OnInit(fun x -> x.ondragend <- handler)
        member this.ondragenter(handler) = this.OnInit(fun x -> x.ondragenter <- handler)
        member this.ondragleave(handler) = this.OnInit(fun x -> x.ondragleave <- handler)
        member this.ondragover(handler) = this.OnInit(fun x -> x.ondragover <- handler)
        member this.ondragstart(handler) = this.OnInit(fun x -> x.ondragstart <- handler)
        member this.ondrop(handler) = this.OnInit(fun x -> x.ondrop <- handler)
        member this.ondurationchange(handler) = this.OnInit(fun x -> x.ondurationchange <- handler)
        member this.onemptied(handler) = this.OnInit(fun x -> x.onemptied <- handler)
        member this.onended(handler) = this.OnInit(fun x -> x.onended <- handler)
        member this.onerror(handler) = this.OnInit(fun x -> x.onerror <- handler)
        member this.onfocus(handler) = this.OnInit(fun x -> x.onfocus <- handler)
        member this.oninput(handler) = this.OnInit(fun x -> x.oninput <- handler)
        member this.onkeydown(handler) = this.OnInit(fun x -> x.onkeydown <- handler)
        member this.onkeypress(handler) = this.OnInit(fun x -> x.onkeypress <- handler)
        member this.onkeyup(handler) = this.OnInit(fun x -> x.onkeyup <- handler)
        member this.onload(handler) = this.OnInit(fun x -> x.onload <- handler)
        member this.onloadeddata(handler) = this.OnInit(fun x -> x.onloadeddata <- handler)
        member this.onloadedmetadata(handler) = this.OnInit(fun x -> x.onloadedmetadata <- handler)
        member this.onloadstart(handler) = this.OnInit(fun x -> x.onloadstart <- handler)
        member this.onmousedown(handler) = this.OnInit(fun x -> x.onmousedown <- handler)
        member this.onmouseenter(handler) = this.OnInit(fun x -> x.onmouseenter <- handler)
        member this.onmouseleave(handler) = this.OnInit(fun x -> x.onmouseleave <- handler)
        member this.onmousemove(handler) = this.OnInit(fun x -> x.onmousemove <- handler)
        member this.onmouseout(handler) = this.OnInit(fun x -> x.onmouseout <- handler)
        member this.onmouseover(handler) = this.OnInit(fun x -> x.onmouseover <- handler)
        member this.onmouseup(handler) = this.OnInit(fun x -> x.onmouseup <- handler)
        member this.onmousewheel(handler) = this.OnInit(fun x -> x.onmousewheel <- handler)
        member this.onpause(handler) = this.OnInit(fun x -> x.onpause <- handler)
        member this.onplay(handler) = this.OnInit(fun x -> x.onplay <- handler)
        member this.onplaying(handler) = this.OnInit(fun x -> x.onplaying <- handler)
        member this.onprogress(handler) = this.OnInit(fun x -> x.onprogress <- handler)
        member this.onratechange(handler) = this.OnInit(fun x -> x.onratechange <- handler)
        member this.onreset(handler) = this.OnInit(fun x -> x.onreset <- handler)
        member this.onscroll(handler) = this.OnInit(fun x -> x.onscroll <- handler)
        member this.onseeked(handler) = this.OnInit(fun x -> x.onseeked <- handler)
        member this.onseeking(handler) = this.OnInit(fun x -> x.onseeking <- handler)
        member this.onselect(handler) = this.OnInit(fun x -> x.onselect <- handler)
        member this.onstalled(handler) = this.OnInit(fun x -> x.onstalled <- handler)
        member this.onsubmit(handler) = this.OnInit(fun x -> x.onsubmit <- handler)
        member this.onsuspend(handler) = this.OnInit(fun x -> x.onsuspend <- handler)
        member this.ontimeupdate(handler) = this.OnInit(fun x -> x.ontimeupdate <- handler)
        member this.onvolumechange(handler) = this.OnInit(fun x -> x.onvolumechange <- handler)
        member this.onwaiting(handler) = this.OnInit(fun x -> x.onwaiting <- handler)
        
    
    type a() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLAnchorElement>( "a" )
        member this.download(value: string) = this.OnEval(fun x -> x.setAttribute("download", value))
        member this.href(value: string) = this.OnEval(fun x -> x.setAttribute("href", value))
        member this.hreflang(value: System.String) = this.OnEval(fun x -> x.setAttribute("hreflang", value))
        member this.ping(value: System.String) = this.OnEval(fun x -> x.setAttribute("ping", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.rel(value: System.String) = this.OnEval(fun x -> x.setAttribute("rel", value))
        member this.target(value: string) = this.OnEval(fun x -> x.setAttribute("target", value))
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type abbr() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "abbr" )
        
        
    
    type address() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "address" )
        
        
    
    type area() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLAreaElement>( "area" )
        member this.alt(value: System.String) = this.OnEval(fun x -> x.setAttribute("alt", value))
        member this.coords(value: string) = this.OnEval(fun x -> x.setAttribute("coords", value))
        member this.download(value: System.String) = this.OnEval(fun x -> x.setAttribute("download", value))
        member this.href(value: System.String) = this.OnEval(fun x -> x.setAttribute("href", value))
        member this.hreflang(value: System.String) = this.OnEval(fun x -> x.setAttribute("hreflang", value))
        member this.ping(value: System.String) = this.OnEval(fun x -> x.setAttribute("ping", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.rel(value: System.String) = this.OnEval(fun x -> x.setAttribute("rel", value))
        member this.shape(value: System.String) = this.OnEval(fun x -> x.setAttribute("shape", value))
        member this.target(value: string) = this.OnEval(fun x -> x.setAttribute("target", value))
        
        
    
    type article() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "article" )
        
        
    
    type aside() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "aside" )
        
        
    
    type audio() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLAudioElement>( "audio" )
        member this.autoplay(value: System.String) = this.OnEval(fun x -> x.setAttribute("autoplay", value))
        member this.controls(value: System.String) = this.OnEval(fun x -> x.setAttribute("controls", value))
        member this.controlslist(value: System.String) = this.OnEval(fun x -> x.setAttribute("controlslist", value))
        member this.crossorigin(value: string) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.disableremoteplayback(value: System.String) = this.OnEval(fun x -> x.setAttribute("disableremoteplayback", value))
        member this.loop(value: System.String) = this.OnEval(fun x -> x.setAttribute("loop", value))
        member this.muted(value: System.String) = this.OnEval(fun x -> x.setAttribute("muted", value))
        member this.preload(value: string) = this.OnEval(fun x -> x.setAttribute("preload", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        
        
    
    type b() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "b" )
        
        
    
    type bdi() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "bdi" )
        
        
    
    type bdo() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "bdo" )
        member this.dir(value: string) = this.OnEval(fun x -> x.setAttribute("dir", value))
        
        
    
    type blockquote() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLQuoteElement>( "blockquote" )
        member this.cite(value: System.String) = this.OnEval(fun x -> x.setAttribute("cite", value))
        
        
    
    type body() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLBodyElement>( "body" )
        member this.alink(value: System.String) = this.OnEval(fun x -> x.setAttribute("alink", value))
        member this.background(value: System.String) = this.OnEval(fun x -> x.setAttribute("background", value))
        member this.bgcolor(value: System.String) = this.OnEval(fun x -> x.setAttribute("bgcolor", value))
        member this.bottommargin(value: System.String) = this.OnEval(fun x -> x.setAttribute("bottommargin", value))
        member this.leftmargin(value: System.String) = this.OnEval(fun x -> x.setAttribute("leftmargin", value))
        member this.link(value: System.String) = this.OnEval(fun x -> x.setAttribute("link", value))
        member this.onafterprint(value: System.String) = this.OnEval(fun x -> x.setAttribute("onafterprint", value))
        member this.onbeforeprint(value: System.String) = this.OnEval(fun x -> x.setAttribute("onbeforeprint", value))
        member this.onbeforeunload(value: System.String) = this.OnEval(fun x -> x.setAttribute("onbeforeunload", value))
        member this.onblur(value: System.String) = this.OnEval(fun x -> x.setAttribute("onblur", value))
        member this.onerror(value: System.String) = this.OnEval(fun x -> x.setAttribute("onerror", value))
        member this.onfocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("onfocus", value))
        member this.onhashchange(value: System.String) = this.OnEval(fun x -> x.setAttribute("onhashchange", value))
        member this.onlanguagechange(value: System.String) = this.OnEval(fun x -> x.setAttribute("onlanguagechange", value))
        member this.onload(value: System.String) = this.OnEval(fun x -> x.setAttribute("onload", value))
        member this.onmessage(value: System.String) = this.OnEval(fun x -> x.setAttribute("onmessage", value))
        member this.onoffline(value: System.String) = this.OnEval(fun x -> x.setAttribute("onoffline", value))
        member this.ononline(value: System.String) = this.OnEval(fun x -> x.setAttribute("ononline", value))
        member this.onpopstate(value: System.String) = this.OnEval(fun x -> x.setAttribute("onpopstate", value))
        member this.onredo(value: System.String) = this.OnEval(fun x -> x.setAttribute("onredo", value))
        member this.onresize(value: System.String) = this.OnEval(fun x -> x.setAttribute("onresize", value))
        member this.onstorage(value: System.String) = this.OnEval(fun x -> x.setAttribute("onstorage", value))
        member this.onundo(value: System.String) = this.OnEval(fun x -> x.setAttribute("onundo", value))
        member this.onunload(value: System.String) = this.OnEval(fun x -> x.setAttribute("onunload", value))
        member this.rightmargin(value: System.String) = this.OnEval(fun x -> x.setAttribute("rightmargin", value))
        member this.text(value: System.String) = this.OnEval(fun x -> x.setAttribute("text", value))
        member this.topmargin(value: System.String) = this.OnEval(fun x -> x.setAttribute("topmargin", value))
        member this.vlink(value: System.String) = this.OnEval(fun x -> x.setAttribute("vlink", value))
        
        
    
    type br() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLBRElement>( "br" )
        
        
    
    type button() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLButtonElement>( "button" )
        member this.autocomplete(value: System.String) = this.OnEval(fun x -> x.setAttribute("autocomplete", value))
        member this.autofocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("autofocus", value))
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.formaction(value: System.String) = this.OnEval(fun x -> x.setAttribute("formaction", value))
        member this.formenctype(value: string) = this.OnEval(fun x -> x.setAttribute("formenctype", value))
        member this.formmethod(value: string) = this.OnEval(fun x -> x.setAttribute("formmethod", value))
        member this.formnovalidate(value: System.String) = this.OnEval(fun x -> x.setAttribute("formnovalidate", value))
        member this.formtarget(value: string) = this.OnEval(fun x -> x.setAttribute("formtarget", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.value(value: System.String) = this.OnEval(fun x -> x.setAttribute("value", value))
        
        
    
    type canvas() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLCanvasElement>( "canvas" )
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.mozOpaque(value: System.String) = this.OnEval(fun x -> x.setAttribute("moz-opaque", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type caption() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableCaptionElement>( "caption" )
        
        
    
    type cite() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "cite" )
        
        
    
    type code() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "code" )
        
        
    
    type col() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableColElement>( "col" )
        member this.span(value: System.String) = this.OnEval(fun x -> x.setAttribute("span", value))
        
        
    
    type colgroup() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableColElement>( "colgroup" )
        member this.span(value: System.String) = this.OnEval(fun x -> x.setAttribute("span", value))
        
        
    
    type datalist() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLDataListElement>( "datalist" )
        
        
    
    type dd() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "dd" )
        member this.nowrap(value: System.String) = this.OnEval(fun x -> x.setAttribute("nowrap", value))
        
        
    
    type del() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLModElement>( "del" )
        member this.cite(value: System.String) = this.OnEval(fun x -> x.setAttribute("cite", value))
        member this.datetime(value: System.String) = this.OnEval(fun x -> x.setAttribute("datetime", value))
        
        
    
    type dfn() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "dfn" )
        
        
    
    type div() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLDivElement>( "div" )
        
        
    
    type dl() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLDListElement>( "dl" )
        
        
    
    type dt() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "dt" )
        
        
    
    type em() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "em" )
        
        
    
    type embed() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLEmbedElement>( "embed" )
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type fieldset() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLFieldSetElement>( "fieldset" )
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        
        
    
    type figcaption() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "figcaption" )
        
        
    
    type figure() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "figure" )
        
        
    
    type footer() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "footer" )
        
        
    
    type form() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLFormElement>( "form" )
        member this.accept(value: System.String) = this.OnEval(fun x -> x.setAttribute("accept", value))
        member this.acceptCharset(value: System.String) = this.OnEval(fun x -> x.setAttribute("accept-charset", value))
        member this.autocapitalize(value: string) = this.OnEval(fun x -> x.setAttribute("autocapitalize", value))
        member this.autocomplete(value: string) = this.OnEval(fun x -> x.setAttribute("autocomplete", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.rel(value: System.String) = this.OnEval(fun x -> x.setAttribute("rel", value))
        
        
    
    type h1() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( "h1" )
        
        
    
    type h2() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( "h2" )
        
        
    
    type h3() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( "h3" )
        
        
    
    type h4() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( "h4" )
        
        
    
    type h5() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( "h5" )
        
        
    
    type h6() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadingElement>( "h6" )
        
        
    
    type head() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHeadElement>( "head" )
        member this.profile(value: System.String) = this.OnEval(fun x -> x.setAttribute("profile", value))
        
        
    
    type header() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "header" )
        
        
    
    type hr() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHRElement>( "hr" )
        member this.align(value: System.String) = this.OnEval(fun x -> x.setAttribute("align", value))
        member this.color(value: System.String) = this.OnEval(fun x -> x.setAttribute("color", value))
        member this.noshade(value: System.String) = this.OnEval(fun x -> x.setAttribute("noshade", value))
        member this.size(value: System.String) = this.OnEval(fun x -> x.setAttribute("size", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type html() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLHtmlElement>( "html" )
        member this.manifest(value: System.String) = this.OnEval(fun x -> x.setAttribute("manifest", value))
        member this.version(value: System.String) = this.OnEval(fun x -> x.setAttribute("version", value))
        member this.xmlns(value: System.String) = this.OnEval(fun x -> x.setAttribute("xmlns", value))
        
        
    
    type i() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "i" )
        
        
    
    type iframe() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLIFrameElement>( "iframe" )
        member this.allow(value: System.String) = this.OnEval(fun x -> x.setAttribute("allow", value))
        member this.allowfullscreen(value: System.String) = this.OnEval(fun x -> x.setAttribute("allowfullscreen", value))
        member this.allowpaymentrequest(value: System.String) = this.OnEval(fun x -> x.setAttribute("allowpaymentrequest", value))
        member this.credentialless(value: System.String) = this.OnEval(fun x -> x.setAttribute("credentialless", value))
        member this.csp(value: System.String) = this.OnEval(fun x -> x.setAttribute("csp", value))
        member this.fetchpriority(value: string) = this.OnEval(fun x -> x.setAttribute("fetchpriority", value))
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.loading(value: string) = this.OnEval(fun x -> x.setAttribute("loading", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.sandbox(value: string) = this.OnEval(fun x -> x.setAttribute("sandbox", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.srcdoc(value: System.String) = this.OnEval(fun x -> x.setAttribute("srcdoc", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type img() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLImageElement>( "img" )
        member this.alt(value: System.String) = this.OnEval(fun x -> x.setAttribute("alt", value))
        member this.crossorigin(value: string) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.decoding(value: string) = this.OnEval(fun x -> x.setAttribute("decoding", value))
        member this.fetchpriority(value: string) = this.OnEval(fun x -> x.setAttribute("fetchpriority", value))
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.ismap(value: System.String) = this.OnEval(fun x -> x.setAttribute("ismap", value))
        member this.loading(value: string) = this.OnEval(fun x -> x.setAttribute("loading", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.sizes(value: System.String) = this.OnEval(fun x -> x.setAttribute("sizes", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.srcset(value: System.String) = this.OnEval(fun x -> x.setAttribute("srcset", value))
        member this.usemap(value: System.String) = this.OnEval(fun x -> x.setAttribute("usemap", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type input() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLInputElement>( "input" )
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type ins() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLModElement>( "ins" )
        member this.cite(value: System.String) = this.OnEval(fun x -> x.setAttribute("cite", value))
        member this.datetime(value: System.String) = this.OnEval(fun x -> x.setAttribute("datetime", value))
        
        
    
    type kbd() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "kbd" )
        
        
    
    type label() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLLabelElement>( "label" )
        member this.for'(value: System.String) = this.OnEval(fun x -> x.setAttribute("for", value))
        
        
    
    type legend() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLLegendElement>( "legend" )
        
        
    
    type li() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLLIElement>( "li" )
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.value(value: System.String) = this.OnEval(fun x -> x.setAttribute("value", value))
        
        
    
    type link() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLLinkElement>( "link" )
        member this.as'(value: System.String) = this.OnEval(fun x -> x.setAttribute("as", value))
        member this.blocking(value: string) = this.OnEval(fun x -> x.setAttribute("blocking", value))
        member this.crossorigin(value: string) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.fetchpriority(value: string) = this.OnEval(fun x -> x.setAttribute("fetchpriority", value))
        member this.href(value: System.String) = this.OnEval(fun x -> x.setAttribute("href", value))
        member this.hreflang(value: System.String) = this.OnEval(fun x -> x.setAttribute("hreflang", value))
        member this.imagesizes(value: System.String) = this.OnEval(fun x -> x.setAttribute("imagesizes", value))
        member this.imagesrcset(value: System.String) = this.OnEval(fun x -> x.setAttribute("imagesrcset", value))
        member this.integrity(value: System.String) = this.OnEval(fun x -> x.setAttribute("integrity", value))
        member this.media(value: System.String) = this.OnEval(fun x -> x.setAttribute("media", value))
        member this.prefetch(value: System.String) = this.OnEval(fun x -> x.setAttribute("prefetch", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.rel(value: System.String) = this.OnEval(fun x -> x.setAttribute("rel", value))
        member this.sizes(value: string) = this.OnEval(fun x -> x.setAttribute("sizes", value))
        member this.title(value: System.String) = this.OnEval(fun x -> x.setAttribute("title", value))
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type main() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "main" )
        
        
    
    type map() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLMapElement>( "map" )
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        
        
    
    type mark() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "mark" )
        
        
    
    type menu() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLMenuElement>( "menu" )
        
        
    
    type meta() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLMetaElement>( "meta" )
        member this.charset(value: System.String) = this.OnEval(fun x -> x.setAttribute("charset", value))
        member this.content(value: System.String) = this.OnEval(fun x -> x.setAttribute("content", value))
        member this.httpEquiv(value: string) = this.OnEval(fun x -> x.setAttribute("http-equiv", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        
        
    
    type nav() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "nav" )
        
        
    
    type noscript() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "noscript" )
        
        
    
    type object() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLObjectElement>( "object" )
        member this.archive(value: System.String) = this.OnEval(fun x -> x.setAttribute("archive", value))
        member this.border(value: System.String) = this.OnEval(fun x -> x.setAttribute("border", value))
        member this.classid(value: System.String) = this.OnEval(fun x -> x.setAttribute("classid", value))
        member this.codebase(value: System.String) = this.OnEval(fun x -> x.setAttribute("codebase", value))
        member this.codetype(value: System.String) = this.OnEval(fun x -> x.setAttribute("codetype", value))
        member this.data(value: System.String) = this.OnEval(fun x -> x.setAttribute("data", value))
        member this.declare(value: System.String) = this.OnEval(fun x -> x.setAttribute("declare", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.standby(value: System.String) = this.OnEval(fun x -> x.setAttribute("standby", value))
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.usemap(value: System.String) = this.OnEval(fun x -> x.setAttribute("usemap", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type ol() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLOListElement>( "ol" )
        member this.reversed(value: System.String) = this.OnEval(fun x -> x.setAttribute("reversed", value))
        member this.start(value: System.String) = this.OnEval(fun x -> x.setAttribute("start", value))
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type optgroup() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLOptGroupElement>( "optgroup" )
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.label(value: System.String) = this.OnEval(fun x -> x.setAttribute("label", value))
        
        
    
    type option() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLOptionElement>( "option" )
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.label(value: System.String) = this.OnEval(fun x -> x.setAttribute("label", value))
        member this.selected(value: System.String) = this.OnEval(fun x -> x.setAttribute("selected", value))
        member this.value(value: System.String) = this.OnEval(fun x -> x.setAttribute("value", value))
        
        
    
    type p() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLParagraphElement>( "p" )
        
        
    
    type pre() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLPreElement>( "pre" )
        member this.cols(value: System.String) = this.OnEval(fun x -> x.setAttribute("cols", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        member this.wrap(value: System.String) = this.OnEval(fun x -> x.setAttribute("wrap", value))
        
        
    
    type progress() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLProgressElement>( "progress" )
        member this.max(value: System.String) = this.OnEval(fun x -> x.setAttribute("max", value))
        member this.value(value: System.String) = this.OnEval(fun x -> x.setAttribute("value", value))
        
        
    
    type q() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLQuoteElement>( "q" )
        member this.cite(value: System.String) = this.OnEval(fun x -> x.setAttribute("cite", value))
        
        
    
    type rp() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "rp" )
        
        
    
    type rt() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "rt" )
        
        
    
    type ruby() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "ruby" )
        
        
    
    type s() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "s" )
        
        
    
    type samp() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "samp" )
        
        
    
    type script() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLScriptElement>( "script" )
        member this.async(value: System.String) = this.OnEval(fun x -> x.setAttribute("async", value))
        member this.blocking(value: string) = this.OnEval(fun x -> x.setAttribute("blocking", value))
        member this.crossorigin(value: System.String) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.defer(value: System.String) = this.OnEval(fun x -> x.setAttribute("defer", value))
        member this.fetchpriority(value: string) = this.OnEval(fun x -> x.setAttribute("fetchpriority", value))
        member this.integrity(value: System.String) = this.OnEval(fun x -> x.setAttribute("integrity", value))
        member this.nomodule(value: System.String) = this.OnEval(fun x -> x.setAttribute("nomodule", value))
        member this.nonce(value: System.String) = this.OnEval(fun x -> x.setAttribute("nonce", value))
        member this.referrerpolicy(value: string) = this.OnEval(fun x -> x.setAttribute("referrerpolicy", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type section() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "section" )
        
        
    
    type select() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLSelectElement>( "select" )
        member this.autocomplete(value: System.String) = this.OnEval(fun x -> x.setAttribute("autocomplete", value))
        member this.autofocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("autofocus", value))
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.multiple(value: System.String) = this.OnEval(fun x -> x.setAttribute("multiple", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.required(value: System.String) = this.OnEval(fun x -> x.setAttribute("required", value))
        member this.size(value: System.String) = this.OnEval(fun x -> x.setAttribute("size", value))
        
        
    
    type small() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "small" )
        
        
    
    type source() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLSourceElement>( "source" )
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.media(value: System.String) = this.OnEval(fun x -> x.setAttribute("media", value))
        member this.sizes(value: System.String) = this.OnEval(fun x -> x.setAttribute("sizes", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.srcset(value: System.String) = this.OnEval(fun x -> x.setAttribute("srcset", value))
        member this.type'(value: System.String) = this.OnEval(fun x -> x.setAttribute("type", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type span() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLSpanElement>( "span" )
        
        
    
    type strong() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "strong" )
        
        
    
    type style() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLStyleElement>( "style" )
        member this.blocking(value: string) = this.OnEval(fun x -> x.setAttribute("blocking", value))
        member this.media(value: System.String) = this.OnEval(fun x -> x.setAttribute("media", value))
        member this.nonce(value: System.String) = this.OnEval(fun x -> x.setAttribute("nonce", value))
        member this.title(value: System.String) = this.OnEval(fun x -> x.setAttribute("title", value))
        
        
    
    type sub() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "sub" )
        
        
    
    type summary() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "summary" )
        
        
    
    type sup() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "sup" )
        
        
    
    type table() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableElement>( "table" )
        
        
    
    type tbody() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableSectionElement>( "tbody" )
        
        
    
    type td() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableCellElement>( "td" )
        member this.colspan(value: System.String) = this.OnEval(fun x -> x.setAttribute("colspan", value))
        member this.headers(value: System.String) = this.OnEval(fun x -> x.setAttribute("headers", value))
        member this.rowspan(value: System.String) = this.OnEval(fun x -> x.setAttribute("rowspan", value))
        
        
    
    type textarea() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTextAreaElement>( "textarea" )
        member this.autocomplete(value: string) = this.OnEval(fun x -> x.setAttribute("autocomplete", value))
        member this.autocorrect(value: string) = this.OnEval(fun x -> x.setAttribute("autocorrect", value))
        member this.autofocus(value: System.String) = this.OnEval(fun x -> x.setAttribute("autofocus", value))
        member this.cols(value: System.String) = this.OnEval(fun x -> x.setAttribute("cols", value))
        member this.disabled(value: System.String) = this.OnEval(fun x -> x.setAttribute("disabled", value))
        member this.form(value: System.String) = this.OnEval(fun x -> x.setAttribute("form", value))
        member this.maxlength(value: System.String) = this.OnEval(fun x -> x.setAttribute("maxlength", value))
        member this.minlength(value: System.String) = this.OnEval(fun x -> x.setAttribute("minlength", value))
        member this.name(value: System.String) = this.OnEval(fun x -> x.setAttribute("name", value))
        member this.placeholder(value: System.String) = this.OnEval(fun x -> x.setAttribute("placeholder", value))
        member this.readonly(value: System.String) = this.OnEval(fun x -> x.setAttribute("readonly", value))
        member this.required(value: System.String) = this.OnEval(fun x -> x.setAttribute("required", value))
        member this.rows(value: System.String) = this.OnEval(fun x -> x.setAttribute("rows", value))
        member this.spellcheck(value: string) = this.OnEval(fun x -> x.setAttribute("spellcheck", value))
        member this.wrap(value: string) = this.OnEval(fun x -> x.setAttribute("wrap", value))
        
        
    
    type tfoot() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableSectionElement>( "tfoot" )
        
        
    
    type th() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableCellElement>( "th" )
        member this.abbr(value: System.String) = this.OnEval(fun x -> x.setAttribute("abbr", value))
        member this.colspan(value: System.String) = this.OnEval(fun x -> x.setAttribute("colspan", value))
        member this.headers(value: System.String) = this.OnEval(fun x -> x.setAttribute("headers", value))
        member this.rowspan(value: System.String) = this.OnEval(fun x -> x.setAttribute("rowspan", value))
        member this.scope(value: string) = this.OnEval(fun x -> x.setAttribute("scope", value))
        
        
    
    type thead() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableSectionElement>( "thead" )
        
        
    
    type title() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTitleElement>( "title" )
        
        
    
    type tr() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTableRowElement>( "tr" )
        
        
    
    type track() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLTrackElement>( "track" )
        member this.default'(value: System.String) = this.OnEval(fun x -> x.setAttribute("default", value))
        member this.kind(value: string) = this.OnEval(fun x -> x.setAttribute("kind", value))
        member this.label(value: System.String) = this.OnEval(fun x -> x.setAttribute("label", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.srclang(value: System.String) = this.OnEval(fun x -> x.setAttribute("srclang", value))
        
        
    
    type u() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "u" )
        
        
    
    type ul() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLUListElement>( "ul" )
        member this.compact(value: System.String) = this.OnEval(fun x -> x.setAttribute("compact", value))
        member this.type'(value: string) = this.OnEval(fun x -> x.setAttribute("type", value))
        
        
    
    type var() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "var" )
        
        
    
    type video() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLVideoElement>( "video" )
        member this.autopictureinpicture(value: System.String) = this.OnEval(fun x -> x.setAttribute("autopictureinpicture", value))
        member this.autoplay(value: System.String) = this.OnEval(fun x -> x.setAttribute("autoplay", value))
        member this.controls(value: System.String) = this.OnEval(fun x -> x.setAttribute("controls", value))
        member this.controlslist(value: System.String) = this.OnEval(fun x -> x.setAttribute("controlslist", value))
        member this.crossorigin(value: string) = this.OnEval(fun x -> x.setAttribute("crossorigin", value))
        member this.disablepictureinpicture(value: System.String) = this.OnEval(fun x -> x.setAttribute("disablepictureinpicture", value))
        member this.disableremoteplayback(value: System.String) = this.OnEval(fun x -> x.setAttribute("disableremoteplayback", value))
        member this.height(value: System.String) = this.OnEval(fun x -> x.setAttribute("height", value))
        member this.loop(value: System.String) = this.OnEval(fun x -> x.setAttribute("loop", value))
        member this.muted(value: System.String) = this.OnEval(fun x -> x.setAttribute("muted", value))
        member this.playsinline(value: System.String) = this.OnEval(fun x -> x.setAttribute("playsinline", value))
        member this.poster(value: System.String) = this.OnEval(fun x -> x.setAttribute("poster", value))
        member this.preload(value: string) = this.OnEval(fun x -> x.setAttribute("preload", value))
        member this.src(value: System.String) = this.OnEval(fun x -> x.setAttribute("src", value))
        member this.width(value: System.String) = this.OnEval(fun x -> x.setAttribute("width", value))
        
        
    
    type wbr() =
        inherit HTMLGlobalAttrsElementBuilder<HTMLElement>( "wbr" )
        
        
    

type Html =
    
    
    
    static member inline a = HtmlElementBuilders.a()
    
    static member inline abbr = HtmlElementBuilders.abbr()
    
    static member inline address = HtmlElementBuilders.address()
    
    static member inline area = HtmlElementBuilders.area()
    
    static member inline article = HtmlElementBuilders.article()
    
    static member inline aside = HtmlElementBuilders.aside()
    
    static member inline audio = HtmlElementBuilders.audio()
    
    static member inline b = HtmlElementBuilders.b()
    
    static member inline bdi = HtmlElementBuilders.bdi()
    
    static member inline bdo = HtmlElementBuilders.bdo()
    
    static member inline blockquote = HtmlElementBuilders.blockquote()
    
    static member inline body = HtmlElementBuilders.body()
    
    static member inline br = HtmlElementBuilders.br()
    
    static member inline button = HtmlElementBuilders.button()
    
    static member inline canvas = HtmlElementBuilders.canvas()
    
    static member inline caption = HtmlElementBuilders.caption()
    
    static member inline cite = HtmlElementBuilders.cite()
    
    static member inline code = HtmlElementBuilders.code()
    
    static member inline col = HtmlElementBuilders.col()
    
    static member inline colgroup = HtmlElementBuilders.colgroup()
    
    static member inline datalist = HtmlElementBuilders.datalist()
    
    static member inline dd = HtmlElementBuilders.dd()
    
    static member inline del = HtmlElementBuilders.del()
    
    static member inline dfn = HtmlElementBuilders.dfn()
    
    static member inline div = HtmlElementBuilders.div()
    
    static member inline dl = HtmlElementBuilders.dl()
    
    static member inline dt = HtmlElementBuilders.dt()
    
    static member inline em = HtmlElementBuilders.em()
    
    static member inline embed = HtmlElementBuilders.embed()
    
    static member inline fieldset = HtmlElementBuilders.fieldset()
    
    static member inline figcaption = HtmlElementBuilders.figcaption()
    
    static member inline figure = HtmlElementBuilders.figure()
    
    static member inline footer = HtmlElementBuilders.footer()
    
    static member inline form = HtmlElementBuilders.form()
    
    static member inline h1 = HtmlElementBuilders.h1()
    
    static member inline h2 = HtmlElementBuilders.h2()
    
    static member inline h3 = HtmlElementBuilders.h3()
    
    static member inline h4 = HtmlElementBuilders.h4()
    
    static member inline h5 = HtmlElementBuilders.h5()
    
    static member inline h6 = HtmlElementBuilders.h6()
    
    static member inline head = HtmlElementBuilders.head()
    
    static member inline header = HtmlElementBuilders.header()
    
    static member inline hr = HtmlElementBuilders.hr()
    
    static member inline html = HtmlElementBuilders.html()
    
    static member inline i = HtmlElementBuilders.i()
    
    static member inline iframe = HtmlElementBuilders.iframe()
    
    static member inline img = HtmlElementBuilders.img()
    
    static member inline input = HtmlElementBuilders.input()
    
    static member inline ins = HtmlElementBuilders.ins()
    
    static member inline kbd = HtmlElementBuilders.kbd()
    
    static member inline label = HtmlElementBuilders.label()
    
    static member inline legend = HtmlElementBuilders.legend()
    
    static member inline li = HtmlElementBuilders.li()
    
    static member inline link = HtmlElementBuilders.link()
    
    static member inline main = HtmlElementBuilders.main()
    
    static member inline map = HtmlElementBuilders.map()
    
    static member inline mark = HtmlElementBuilders.mark()
    
    static member inline menu = HtmlElementBuilders.menu()
    
    static member inline meta = HtmlElementBuilders.meta()
    
    static member inline nav = HtmlElementBuilders.nav()
    
    static member inline noscript = HtmlElementBuilders.noscript()
    
    static member inline object = HtmlElementBuilders.object()
    
    static member inline ol = HtmlElementBuilders.ol()
    
    static member inline optgroup = HtmlElementBuilders.optgroup()
    
    static member inline option = HtmlElementBuilders.option()
    
    static member inline p = HtmlElementBuilders.p()
    
    static member inline pre = HtmlElementBuilders.pre()
    
    static member inline progress = HtmlElementBuilders.progress()
    
    static member inline q = HtmlElementBuilders.q()
    
    static member inline rp = HtmlElementBuilders.rp()
    
    static member inline rt = HtmlElementBuilders.rt()
    
    static member inline ruby = HtmlElementBuilders.ruby()
    
    static member inline s = HtmlElementBuilders.s()
    
    static member inline samp = HtmlElementBuilders.samp()
    
    static member inline script = HtmlElementBuilders.script()
    
    static member inline section = HtmlElementBuilders.section()
    
    static member inline select = HtmlElementBuilders.select()
    
    static member inline small = HtmlElementBuilders.small()
    
    static member inline source = HtmlElementBuilders.source()
    
    static member inline span = HtmlElementBuilders.span()
    
    static member inline strong = HtmlElementBuilders.strong()
    
    static member inline style = HtmlElementBuilders.style()
    
    static member inline sub = HtmlElementBuilders.sub()
    
    static member inline summary = HtmlElementBuilders.summary()
    
    static member inline sup = HtmlElementBuilders.sup()
    
    static member inline table = HtmlElementBuilders.table()
    
    static member inline tbody = HtmlElementBuilders.tbody()
    
    static member inline td = HtmlElementBuilders.td()
    
    static member inline textarea = HtmlElementBuilders.textarea()
    
    static member inline tfoot = HtmlElementBuilders.tfoot()
    
    static member inline th = HtmlElementBuilders.th()
    
    static member inline thead = HtmlElementBuilders.thead()
    
    static member inline title = HtmlElementBuilders.title()
    
    static member inline tr = HtmlElementBuilders.tr()
    
    static member inline track = HtmlElementBuilders.track()
    
    static member inline u = HtmlElementBuilders.u()
    
    static member inline ul = HtmlElementBuilders.ul()
    
    static member inline var = HtmlElementBuilders.var()
    
    static member inline video = HtmlElementBuilders.video()
    
    static member inline wbr = HtmlElementBuilders.wbr()
    
